### ISSUE TITLE
很赞的项目，有几个问题想请教一下

### ISSUE THREAD

**Issue by weiccTest** [vvpvvp/UMock#1]
![image](https://cloud.githubusercontent.com/assets/7098301/20911053/536d3f16-bba0-11e6-90ab-6c5fcb50ab29.png)
为什么总是返回404，我哪里配置有问题吗？
方便可以加一下我的微信（18620553068）吗？

**Comment by vvpvvp** [comment]
你配置是已/api为开头的项目吗？
