### ISSUE TITLE
node 10.12.0 安装失败，应该是 leveldown@1.9.0 编译失败了

### ISSUE THREAD

**Issue by XGHeaven** [vvpvvp/UMock#2]
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/9291212/48327622-98dfc300-e67a-11e8-8525-3bd2f8415bd7.png">

版本：
- node: v10.12.0
- node-gyp v3.8.0

我看了下，官网应该是 4.x 的版本了，估计是某个依赖导致版本太低，试试更新个依赖？

**Comment by vvpvvp** [comment]
npm 版本是多少？

**Comment by XGHeaven** [comment]
v6.4.1

**Comment by vvpvvp** [comment]
我建议你试试使用git clone的方式，更新也比较方便。
我刚刚升级了版本，发现的确有问题，我看下问题。

**Comment by vvpvvp** [comment]
我已经更新了版本了。
你可以安装umock@latest。
多谢你的反馈。
